window.Modernizr=function(j,f,p){function v(a){q.cssText=a}function Y(a,b){return v(t.join(a+";")+(b||""))}function w(a,b){return typeof a===b}function y(a,b){return(""+a).indexOf(b)!==-1}function H(a,b){for(var c in a)if(q[a[c]]!==p&&(!b||b(a[c],I)))return true}function r(a,b){var c=a.charAt(0).toUpperCase()+a.substr(1);a=(a+" "+J.join(c+" ")+c).split(" ");return!!H(a,b)}function Z(){h.input=function(a){for(var b=0,c=a.length;b<c;b++)O[a[b]]=!!(a[b]in i);return O}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));
h.inputtypes=function(a){for(var b=0,c,e,g=a.length;b<g;b++){i.setAttribute("type",e=a[b]);if(c=i.type!=="text"){i.value=K;i.style.cssText="position:absolute;visibility:hidden;";if(/^range$/.test(e)&&i.style.WebkitAppearance!==p){k.appendChild(i);c=f.defaultView;c=c.getComputedStyle&&c.getComputedStyle(i,null).WebkitAppearance!=="textfield"&&i.offsetHeight!==0;k.removeChild(i)}else if(!/^(search|tel)$/.test(e))if(/^(url|email)$/.test(e))c=i.checkValidity&&i.checkValidity()===false;else if(/^color$/.test(e)){k.appendChild(i);
c=i.value!=K;k.removeChild(i)}else c=i.value!=K}P[a[b]]=!!c}return P}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var h={},k=f.documentElement,Q=f.head||f.getElementsByTagName("head")[0],I=f.createElement("modernizr"),q=I.style,i=f.createElement("input"),K=":)",R=Object.prototype.toString,t=" -webkit- -moz- -o- -ms- -khtml- ".split(" "),J="Webkit Moz O ms Khtml".split(" "),C={svg:"http://www.w3.org/2000/svg"},d={},P={},O={},S=[],D,T=function(a){var b=
f.createElement("style"),c=f.createElement("div");b.textContent=a+"{#modernizr{height:3px}}";Q.appendChild(b);c.id="modernizr";k.appendChild(c);a=c.offsetHeight===3;b.parentNode.removeChild(b);c.parentNode.removeChild(c);return!!a},L=function(){function a(c,e){e=e||f.createElement(b[c]||"div");c="on"+c;var g=c in e;if(!g){e.setAttribute||(e=f.createElement("div"));if(e.setAttribute&&e.removeAttribute){e.setAttribute(c,"");g=w(e[c],"function");w(e[c],p)||(e[c]=p);e.removeAttribute(c)}}return g}var b=
{select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return a}(),M={}.hasOwnProperty,U;U=!w(M,p)&&!w(M.call,p)?function(a,b){return M.call(a,b)}:function(a,b){return b in a&&w(a.constructor.prototype[b],p)};d.flexbox=function(){function a(n,o,z,A){o+=":";n.style.cssText=(o+t.join(z+";"+o)).slice(0,-o.length)+(A||"")}function b(n,o,z,A){n.style.cssText=t.join(o+":"+z+";")+(A||"")}var c=f.createElement("div"),e=f.createElement("div");a(c,"display","box","width:42px;padding:0;");
b(e,"box-flex","1","width:10px;");c.appendChild(e);k.appendChild(c);var g=e.offsetWidth===42;c.removeChild(e);k.removeChild(c);return g};d.canvas=function(){var a=f.createElement("canvas");return!!(a.getContext&&a.getContext("2d"))};d.canvastext=function(){return!!(h.canvas&&w(f.createElement("canvas").getContext("2d").fillText,"function"))};d.webgl=function(){return!!j.WebGLRenderingContext};d.touch=function(){return"ontouchstart"in j||T("@media ("+t.join("touch-enabled),(")+"modernizr)")};d.geolocation=
function(){return!!navigator.geolocation};d.postmessage=function(){return!!j.postMessage};d.websqldatabase=function(){return!!j.openDatabase};d.indexedDB=function(){for(var a=-1,b=J.length;++a<b;){var c=J[a].toLowerCase();if(j[c+"_indexedDB"]||j[c+"IndexedDB"])return true}return false};d.hashchange=function(){return L("hashchange",j)&&(f.documentMode===p||f.documentMode>7)};d.history=function(){return!!(j.history&&history.pushState)};d.draganddrop=function(){return L("dragstart")&&L("drop")};d.websockets=
function(){return"WebSocket"in j};d.rgba=function(){v("background-color:rgba(150,255,150,.5)");return y(q.backgroundColor,"rgba")};d.hsla=function(){v("background-color:hsla(120,40%,100%,.5)");return y(q.backgroundColor,"rgba")||y(q.backgroundColor,"hsla")};d.multiplebgs=function(){v("background:url(//:),url(//:),red url(//:)");return/(url\s*\(.*?){3}/.test(q.background)};d.backgroundsize=function(){return r("backgroundSize")};d.borderimage=function(){return r("borderImage")};d.borderradius=function(){return r("borderRadius",
"",function(a){return y(a,"orderRadius")})};d.boxshadow=function(){return r("boxShadow")};d.textshadow=function(){return f.createElement("div").style.textShadow===""};d.opacity=function(){Y("opacity:.55");return/^0.55$/.test(q.opacity)};d.cssanimations=function(){return r("animationName")};d.csscolumns=function(){return r("columnCount")};d.cssgradients=function(){v(("background-image:"+t.join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+t.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,
-17));return y(q.backgroundImage,"gradient")};d.cssreflections=function(){return r("boxReflect")};d.csstransforms=function(){return!!H(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"])};d.csstransforms3d=function(){var a=!!H(["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);if(a&&"webkitPerspective"in k.style)a=T("@media ("+t.join("transform-3d),(")+"modernizr)");return a};d.csstransitions=function(){return r("transitionProperty")};
d.fontface=function(){var a,b,c=Q||k,e=f.createElement("style");b=f.implementation||{hasFeature:function(){return false}};e.type="text/css";c.insertBefore(e,c.firstChild);a=e.sheet||e.styleSheet;b=(b.hasFeature("CSS2","")?function(g){if(!(a&&g))return false;var n=false;try{a.insertRule(g,0);n=/src/i.test(a.cssRules[0].cssText);a.deleteRule(a.cssRules.length-1)}catch(o){}return n}:function(g){if(!(a&&g))return false;a.cssText=g;return a.cssText.length!==0&&/src/i.test(a.cssText)&&a.cssText.replace(/\r+|\n+/g,
"").indexOf(g.split(" ")[0])===0})('@font-face { font-family: "font"; src: url(data:,); }');c.removeChild(e);return b};d.video=function(){var a=f.createElement("video"),b=!!a.canPlayType;if(b){b=new Boolean(b);b.ogg=a.canPlayType('video/ogg; codecs="theora"');b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"')||a.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"');b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"')}return b};d.audio=function(){var a=f.createElement("audio"),b=!!a.canPlayType;
if(b){b=new Boolean(b);b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"');b.mp3=a.canPlayType("audio/mpeg;");b.wav=a.canPlayType('audio/wav; codecs="1"');b.m4a=a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")}return b};d.localstorage=function(){try{return!!localStorage.getItem}catch(a){return false}};d.sessionstorage=function(){try{return!!sessionStorage.getItem}catch(a){return false}};d.webWorkers=function(){return!!j.Worker};d.applicationcache=function(){return!!j.applicationCache};d.svg=
function(){return!!f.createElementNS&&!!f.createElementNS(C.svg,"svg").createSVGRect};d.inlinesvg=function(){var a=f.createElement("div");a.innerHTML="<svg/>";return(a.firstChild&&a.firstChild.namespaceURI)==C.svg};d.smil=function(){return!!f.createElementNS&&/SVG/.test(R.call(f.createElementNS(C.svg,"animate")))};d.svgclippaths=function(){return!!f.createElementNS&&/SVG/.test(R.call(f.createElementNS(C.svg,"clipPath")))};for(var N in d)if(U(d,N)){D=N.toLowerCase();h[D]=d[N]();S.push((h[D]?"":"no-")+
D)}h.input||Z();h.crosswindowmessaging=h.postmessage;h.historymanagement=h.history;h.addTest=function(a,b){a=a.toLowerCase();if(!h[a]){b=!!b();k.className+=" "+(b?"":"no-")+a;h[a]=b;return h}};v("");I=i=null;j.attachEvent&&function(){var a=f.createElement("div");a.innerHTML="<elem></elem>";return a.childNodes.length!==1}()&&function(a,b){function c(s){for(var l=-1;++l<n;)s.createElement(g[l])}function e(s,l){for(var u=-1,m=s.length,E,V=[];++u<m;){E=s[u];if((l=E.media||l)!="screen")V.push(e(E.imports,
l),E.cssText)}return V.join("")}var g="abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video".split("|"),n=g.length,o=new RegExp("(^|\\s)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)","gi"),z=new RegExp("<(/*)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)",
"gi"),A=new RegExp("(^|[^\\n]*?\\s)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)([^\\n]*)({[\\n\\w\\W]*?})","gi"),W=b.createDocumentFragment(),F=b.documentElement,X=F.firstChild,B=b.createElement("body"),G=b.createElement("style"),x;c(b);c(W);X.insertBefore(G,X.firstChild);G.media="print";a.attachEvent("onbeforeprint",function(){var s=-1,l=e(b.styleSheets,"all"),u=[],m;for(x=x||b.body;(m=A.exec(l))!=null;)u.push((m[1]+
m[2]+m[3]).replace(o,"$1.iepp_$2")+m[4]);for(G.styleSheet.cssText=u.join("\n");++s<n;){l=b.getElementsByTagName(g[s]);u=l.length;for(m=-1;++m<u;)if(l[m].className.indexOf("iepp_")<0)l[m].className+=" iepp_"+g[s]}W.appendChild(x);F.appendChild(B);B.className=x.className;B.innerHTML=x.innerHTML.replace(z,"<$1font")});a.attachEvent("onafterprint",function(){B.innerHTML="";F.removeChild(B);F.appendChild(x);G.styleSheet.cssText=""})}(j,f);h._enableHTML5=true;h._version="1.7";k.className=k.className.replace(/\bno-js\b/,
"")+" js "+S.join(" ");return h}(this,this.document);